-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 10, 2026 at 06:48 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `resep_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `favorit`
--

CREATE TABLE `favorit` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `resep_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `favorit`
--

INSERT INTO `favorit` (`id`, `user_id`, `resep_id`, `created_at`) VALUES
(27, 1, 2, '2026-02-10 01:56:55');

-- --------------------------------------------------------

--
-- Table structure for table `rating`
--

CREATE TABLE `rating` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `resep_id` int(11) NOT NULL,
  `rating` int(11) DEFAULT NULL CHECK (`rating` >= 1 and `rating` <= 5),
  `komentar` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `rating`
--

INSERT INTO `rating` (`id`, `user_id`, `resep_id`, `rating`, `komentar`, `created_at`) VALUES
(1, 1, 2, NULL, 'wuenak', '2026-02-10 02:43:46');

-- --------------------------------------------------------

--
-- Table structure for table `resep`
--

CREATE TABLE `resep` (
  `id` int(11) NOT NULL,
  `judul` varchar(200) NOT NULL,
  `deskripsi` text DEFAULT NULL,
  `bahan` text NOT NULL,
  `langkah` text NOT NULL,
  `waktu` int(11) DEFAULT NULL COMMENT 'Waktu memasak dalam menit',
  `porsi` int(11) DEFAULT NULL,
  `tingkat_kesulitan` enum('Mudah','Sedang','Sulit') DEFAULT 'Sedang',
  `kategori` varchar(50) DEFAULT NULL,
  `gambar_url` varchar(500) DEFAULT NULL,
  `kalori` int(11) DEFAULT NULL COMMENT 'Perkiraan kalori per porsi',
  `protein` decimal(5,1) DEFAULT NULL COMMENT 'Perkiraan protein (g) per porsi',
  `karbohidrat` decimal(5,1) DEFAULT NULL COMMENT 'Perkiraan karbohidrat (g) per porsi',
  `lemak` decimal(5,1) DEFAULT NULL COMMENT 'Perkiraan lemak (g) per porsi',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `resep`
--

INSERT INTO `resep` (`id`, `judul`, `deskripsi`, `bahan`, `langkah`, `waktu`, `porsi`, `tingkat_kesulitan`, `kategori`, `gambar_url`, `kalori`, `protein`, `karbohidrat`, `lemak`, `created_at`) VALUES
(1, 'Nasi Goreng Spesial', 'Nasi goreng dengan bumbu spesial dan topping lengkap', 'Nasi putih 2 piring, Bawang putih 3 siung, Kecap manis 2 sdm, Telur 2 butir, Ayam suwir 100 gram, Daun bawang 2 batang, Minyak goreng 2 sdm, Garam secukupnya', '1. Tumis bawang putih hingga harum\n2. Masukkan telur, orak-arik\n3. Tambahkan ayam suwir\n4. Masukkan nasi, kecap, dan garam\n5. Aduk rata hingga matang\n6. Taburi daun bawang\n7. Selesai. Silahkan dinikmati!', 20, 2, 'Mudah', 'Makanan Utama', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80', 550, 22.0, 65.0, 22.0, '2026-02-01 12:16:50'),
(2, 'Soto Ayam Lamongan', 'Soto ayam khas Lamongan dengan kuah bening', 'Ayam 1 ekor, Serai 2 batang, Daun jeruk 5 lembar, Jahe 2 cm, Kunyit 4 cm, Bawang merah 8 butir, Bawang putih 5 siung, Lada 1 sdt, Garam secukupnya, Soun 100 gram, Tauge 100 gram, Kol 100 gram', '1. Rebus ayam hingga matang\n2. Tumis bumbu halus hingga harum\n3. Masukkan bumbu tumis ke dalam rebusan ayam\n4. Tambahkan serai dan daun jeruk\n5. Sajikan dengan pelengkap\n6. Selesai. Silahkan dinikmati!', 60, 4, 'Sedang', 'Sup', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80', 320, 24.0, 28.0, 12.0, '2026-02-01 12:16:50'),
(3, 'Brownies Coklat Lumer', 'Brownies coklat dengan tekstur lembut dan lumer', 'Coklat batang 200 gram, Mentega 150 gram, Telur 3 butir, Gula pasir 150 gram, Tepung terigu 100 gram, Coklat bubuk 50 gram, Kacang kenari 50 gram', '1. Lelehkan coklat dan mentega\n2. Kocok telur dan gula hingga mengembang\n3. Campurkan lelehan coklat ke dalam adonan telur\n4. Ayak tepung terigu dan coklat bubuk\n5. Panggang dalam oven 180°C selama 30 menit\n6. Selesai. Silahkan dinikmati!', 45, 8, 'Mudah', 'Dessert', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80', 420, 6.0, 52.0, 22.0, '2026-02-01 12:16:50'),
(4, 'Ayam Rica-Rica Manado', 'Ayam pedas rempah khas Manado dengan aroma daun jeruk', 'Ayam 500 gram, cabai merah 10 buah, cabai rawit 5 buah, bawang merah 6 siung, bawang putih 4 siung, jahe 2 cm, serai 1 batang, daun jeruk 4 lembar, garam, gula, minyak', '1. Cuci bersih ayam, potong sesuai selera, lumuri sedikit garam dan jeruk nipis\n2. Haluskan cabai, bawang merah, bawang putih, dan jahe\n3. Panaskan minyak lalu tumis bumbu halus hingga harum dan matang\n4. Masukkan ayam, aduk hingga berubah warna\n5. Tambahkan serai dan daun jeruk, beri sedikit air\n6. Masak hingga ayam empuk dan bumbu meresap, koreksi rasa\n7. Sajikan hangat\n8. Selesai. Silahkan dinikmati!', 40, 3, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?ayam-pedas', 380, 32.0, 8.0, 22.0, '2026-02-01 12:16:50'),
(5, 'Ikan Goreng Sambal Dabu-Dabu', 'Ikan goreng renyah dengan sambal segar khas Sulawesi', 'Ikan kembung 2 ekor, jeruk nipis, garam, minyak, tomat 2 buah, bawang merah 5 siung, cabai rawit 6 buah, daun bawang, minyak panas', '1. Bersihkan ikan, lumuri garam dan jeruk nipis, diamkan 10 menit\n2. Panaskan minyak banyak, goreng ikan hingga matang dan renyah, tiriskan\n3. Iris tomat, bawang merah, cabai, dan daun bawang\n4. Campur semua bahan sambal, beri garam secukupnya\n5. Siram minyak panas ke sambal lalu aduk rata\n6. Sajikan ikan goreng dengan sambal dabu-dabu di atasnya\n7. Selesai. Silahkan dinikmati!', 30, 2, 'Mudah', 'Makanan Utama', 'https://source.unsplash.com/500x400/?ikan-goreng', 450, 35.0, 6.0, 30.0, '2026-02-01 12:16:50'),
(6, 'Tumis Kangkung Terasi', 'Sayur tumis sederhana dengan aroma terasi', 'Kangkung 1 ikat, bawang putih 3 siung, bawang merah 4 siung, cabai 4 buah, terasi 1 sdt, saus tiram 1 sdm, garam, minyak', '1. Petik dan cuci bersih kangkung, tiriskan\n2. Haluskan bawang merah, bawang putih, cabai, dan terasi\n3. Panaskan minyak, tumis bumbu hingga harum\n4. Masukkan kangkung, aduk cepat dengan api besar\n5. Tambahkan saus tiram dan garam, aduk rata\n6. Masak sebentar saja hingga layu lalu angkat\n7. Selesai. Silahkan dinikmati!', 10, 2, 'Mudah', 'Sayuran', 'https://source.unsplash.com/500x400/?kangkung', 160, 5.0, 10.0, 11.0, '2026-02-01 12:16:50'),
(7, 'Bakwan Jagung', 'Gorengan jagung manis renyah', 'Jagung manis 2 tongkol, tepung terigu 150 gram, telur 1 butir, daun bawang, bawang putih 2 siung, garam, merica, air secukupnya, minyak', '1. Pipil jagung, campur dengan tepung, telur, irisan daun bawang, dan bumbu halus\n2. Tambahkan air sedikit demi sedikit hingga adonan kental\n3. Panaskan minyak banyak\n4. Ambil satu sendok adonan, goreng hingga kuning keemasan\n5. Balik agar matang merata, lalu tiriskan\n6. Sajikan hangat\n7. Selesai. Silahkan dinikmati!', 20, 4, 'Mudah', 'Snack', 'https://source.unsplash.com/500x400/?bakwan', 280, 6.0, 32.0, 14.0, '2026-02-01 12:16:50'),
(8, 'Pisang Goreng Madu', 'Pisang goreng manis legit dengan madu', 'Pisang kepok 5 buah, tepung terigu 120 gram, tepung beras 2 sdm, gula 2 sdm, madu 3 sdm, air, minyak', '1. Campur tepung terigu, tepung beras, gula, dan air hingga adonan agak kental\n2. Kupas dan belah pisang\n3. Celupkan pisang ke adonan hingga terbalut rata\n4. Goreng dalam minyak panas sampai kuning kecoklatan\n5. Angkat dan tiriskan\n6. Sajikan dengan siraman madu\n7. Selesai. Silahkan dinikmati!', 15, 3, 'Mudah', 'Dessert', 'https://source.unsplash.com/500x400/?pisang-goreng', 330, 4.0, 50.0, 13.0, '2026-02-01 12:16:50'),
(9, 'Sate Ayam Madura', 'Sate ayam bakar dengan bumbu kacang manis gurih khas Madura', 'Dada ayam 500 gram, tusuk sate, kacang tanah 150 gram, bawang putih 3 siung, kemiri 2 butir, kecap manis 4 sdm, gula merah, garam, minyak', '1. Potong ayam kecil-kecil lalu tusuk dengan tusuk sate\n2. Haluskan kacang goreng dan bumbu, campur kecap manis dan air hingga jadi saus\n3. Olesi sate dengan bumbu\n4. Bakar sate sambil dibolak-balik dan dioles bumbu hingga matang\n5. Sajikan dengan sisa saus kacang dan lontong\n6. Selesai. Silahkan dinikmati!', 35, 4, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?sate-ayam', 520, 35.0, 28.0, 28.0, '2026-02-01 12:16:50'),
(10, 'Gado-Gado Jakarta', 'Salad sayuran rebus dengan saus kacang kental dan gurih', 'Tauge 100 gram, kacang panjang, kol, kentang rebus, tahu goreng, tempe goreng, telur rebus, kacang tanah 150 gram, bawang putih 2 siung, gula merah, garam, air asam jawa', '1. Rebus semua sayuran\n2. Goreng tahu dan tempe\n3. Haluskan kacang dan bumbu\n4. Tambahkan air hingga jadi saus\n5. Siram saus ke sayuran lalu sajikan\n6. Selesai. Silahkan dinikmati!', 25, 3, 'Mudah', 'Salad', 'https://source.unsplash.com/500x400/?gado-gado', 420, 16.0, 38.0, 22.0, '2026-02-01 12:16:50'),
(11, 'Rawon Daging Jawa Timur', 'Sup daging berkuah hitam khas kluwek yang gurih', 'Daging sapi 500 gram, kluwek 5 buah, bawang merah 6 siung, bawang putih 4 siung, serai 1 batang, daun jeruk 3 lembar, garam, gula, minyak', '1. Rebus daging hingga empuk lalu potong-potong\n2. Haluskan bawang merah, bawang putih, dan kluwek\n3. Tumis bumbu halus hingga harum dan matang\n4. Masukkan bumbu tumis ke kuah rebusan daging\n5. Tambahkan serai dan daun jeruk\n6. Masak hingga kuah hitam pekat dan meresap\n7. Koreksi rasa lalu sajikan hangat\n8. Selesai. Silahkan dinikmati!', 90, 4, 'Sedang', 'Sup', 'https://source.unsplash.com/500x400/?rawon', 360, 26.0, 10.0, 24.0, '2026-02-01 12:16:50'),
(12, 'Nasi Uduk Betawi', 'Nasi gurih santan dengan aroma rempah', 'Beras 500 gram, santan 600 ml, daun salam, serai, garam', '1. Cuci beras hingga bersih\n2. Campurkan santan, serai, daun salam, dan garam\n3. Masak beras bersama santan hingga air menyusut\n4. Aduk rata lalu kukus 10-15 menit hingga matang\n5. Aduk kembali agar pulen\n6. Sajikan dengan lauk pelengkap\n7. Selesai. Silahkan dinikmati!', 35, 4, 'Mudah', 'Makanan Utama', 'https://source.unsplash.com/500x400/?nasi-uduk', 340, 6.0, 52.0, 12.0, '2026-02-01 12:16:50'),
(13, 'Pempek Palembang', 'Olahan ikan dan sagu dengan kuah cuko asam manis pedas', 'Ikan tenggiri giling 300 gram, tepung sagu 200 gram, bawang putih 3 siung, garam, gula merah, asam jawa', '1. Campur ikan giling dengan bawang putih halus dan garam\n2. Tambahkan tepung sagu sedikit demi sedikit sambil diuleni\n3. Bentuk adonan sesuai selera\n4. Rebus hingga pempek mengapung lalu tiriskan\n5. Goreng sebentar hingga kecoklatan\n6. Sajikan dengan kuah cuko\n7. Selesai. Silahkan dinikmati!', 60, 4, 'Sedang', 'Snack', 'https://source.unsplash.com/500x400/?pempek', 360, 14.0, 52.0, 10.0, '2026-02-01 12:16:50'),
(14, 'Soto Betawi Santan', 'Soto daging kuah santan kental gurih', 'Daging sapi 400 gram, santan 500 ml, susu cair 200 ml, bawang merah, bawang putih, pala, serai', '1. Rebus daging hingga empuk lalu potong-potong\n2. Haluskan bawang, bawang putih, dan pala\n3. Tumis bumbu hingga harum\n4. Masukkan santan dan susu sambil diaduk agar tidak pecah\n5. Tambahkan daging dan serai\n6. Masak hingga kuah mendidih dan meresap\n7. Sajikan hangat\n8. Selesai. Silahkan dinikmati!', 60, 3, 'Sedang', 'Sup', 'https://source.unsplash.com/500x400/?soto-betawi', 480, 24.0, 12.0, 36.0, '2026-02-01 12:16:50'),
(15, 'Ayam Bakar Taliwang', 'Ayam bakar pedas manis khas Lombok', 'Ayam 1 ekor, cabai merah 8 buah, bawang putih 4 siung, terasi, gula merah, kecap manis', '1. Bersihkan ayam lalu belah tidak putus\n2. Haluskan semua bumbu\n3. Lumuri ayam dengan bumbu hingga merata\n4. Diamkan 15-20 menit agar meresap\n5. Bakar ayam sambil dioles sisa bumbu\n6. Balik hingga matang dan sedikit karamel\n7. Sajikan panas\n8. Selesai. Silahkan dinikmati!', 40, 3, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?ayam-bakar', 420, 34.0, 6.0, 28.0, '2026-02-01 12:16:50'),
(16, 'Perkedel Kentang', 'Perkedel lembut dari kentang goreng', 'Kentang 500 gram, telur 1 butir, bawang putih 2 siung, merica, garam, minyak', '1. Kupas kentang lalu goreng hingga matang\n2. Haluskan kentang selagi panas\n3. Tambahkan bawang putih halus, merica, garam, dan telur\n4. Aduk rata lalu bentuk bulat pipih\n5. Panaskan minyak dan goreng hingga kecoklatan\n6. Tiriskan lalu sajikan\n7. Selesai. Silahkan dinikmati!', 25, 4, 'Mudah', 'Snack', 'https://source.unsplash.com/500x400/?perkedel', 260, 5.0, 28.0, 14.0, '2026-02-01 12:16:50'),
(17, 'Sayur Asem Sunda', 'Sayur kuah asam segar dengan aneka sayuran', 'Labu siam, kacang panjang, jagung, melinjo, asam jawa, bawang merah, bawang putih', '1. Rebus air bersama bawang merah dan bawang putih halus\n2. Tambahkan asam jawa\n3. Masukkan jagung dan sayuran keras terlebih dahulu\n4. Tambahkan sayuran lain\n5. Masak hingga semua matang\n6. Tambahkan garam dan gula secukupnya\n7. Sajikan hangat\n8. Selesai. Silahkan dinikmati!', 30, 4, 'Mudah', 'Sayuran', 'https://source.unsplash.com/500x400/?sayur-asem', 120, 4.0, 18.0, 4.0, '2026-02-01 12:16:50'),
(18, 'Martabak Telur Mini', 'Martabak gurih isi telur dan daging cincang', 'Kulit lumpia, telur 3 butir, daging cincang 150 gram, daun bawang, bawang putih, garam', '1. Tumis daging cincang dengan bawang putih hingga matang\n2. Campurkan daging dengan telur dan daun bawang\n3. Ambil satu lembar kulit lumpia lalu isi adonan\n4. Lipat rapi berbentuk kotak\n5. Goreng dalam minyak panas hingga keemasan\n6. Tiriskan dan sajikan hangat\n7. Selesai. Silahkan dinikmati!', 20, 3, 'Sedang', 'Snack', 'https://source.unsplash.com/500x400/?martabak', 430, 18.0, 28.0, 28.0, '2026-02-01 12:16:50'),
(19, 'Bubur Ayam Kampung', 'Bubur lembut dengan topping ayam gurih', 'Beras 200 gram, ayam suwir, kaldu ayam, daun bawang, bawang goreng, kecap', '1. Cuci beras lalu masak dengan air banyak hingga menjadi bubur lembut\n2. Tambahkan kaldu ayam dan aduk rata\n3. Masak hingga tekstur kental dan halus\n4. Siapkan mangkuk lalu tuang bubur\n5. Tambahkan ayam suwir, daun bawang, dan bawang goreng\n6. Beri kecap sesuai selera lalu sajikan hangat\n7. Selesai. Silahkan dinikmati!', 40, 3, 'Mudah', 'Makanan Utama', 'https://source.unsplash.com/500x400/?bubur-ayam', 310, 16.0, 42.0, 9.0, '2026-02-01 12:16:50'),
(20, 'Rendang Daging Padang', 'Daging sapi dimasak lama dengan santan dan rempah hingga kering dan gurih', 'Daging sapi 500 gram, santan 1 liter, serai 2 batang, daun jeruk 4 lembar, lengkuas, cabai merah 10 buah, bawang merah 8 siung, bawang putih 5 siung, garam, gula', '1. Potong daging sesuai selera\n2. Haluskan cabai dan semua bumbu\n3. Tumis bumbu hingga harum\n4. Masukkan daging dan aduk rata\n5. Tuang santan, serai, daun jeruk, dan lengkuas\n6. Masak dengan api kecil sambil diaduk hingga santan menyusut\n7. Masak terus sampai bumbu mengering dan berwarna gelap\n8. Sajikan hangat\n9. Selesai. Silahkan dinikmati!', 120, 4, 'Sulit', 'Makanan Utama', 'https://source.unsplash.com/500x400/?rendang', 650, 45.0, 8.0, 52.0, '2026-02-01 12:16:50'),
(21, 'Mie Goreng Jawa', 'Mie goreng manis gurih dengan bumbu khas kaki lima', 'Mie telur 2 porsi, bawang putih 3 siung, bawang merah 4 siung, kecap manis 3 sdm, kol, sawi, telur 1 butir, ayam suwir, garam, minyak', '1. Rebus mie hingga setengah matang lalu tiriskan\n2. Tumis bawang merah dan bawang putih hingga harum\n3. Masukkan telur lalu orak-arik\n4. Tambahkan ayam dan sayuran\n5. Masukkan mie, kecap manis, dan garam\n6. Aduk hingga tercampur rata dan matang\n7. Sajikan panas\n8. Selesai. Silahkan dinikmati!', 25, 2, 'Mudah', 'Makanan Utama', 'https://source.unsplash.com/500x400/?mie-goreng', 480, 18.0, 72.0, 16.0, '2026-02-01 12:16:50'),
(22, 'Capcay Kuah', 'Tumis aneka sayuran dengan kuah gurih kental', 'Wortel, kol, kembang kol, sawi, bakso, bawang putih 3 siung, saus tiram 2 sdm, tepung maizena 1 sdm, garam, merica', '1. Potong semua sayuran\n2. Tumis bawang putih hingga harum\n3. Masukkan bakso dan sayuran keras terlebih dahulu\n4. Tambahkan air secukupnya\n5. Bumbui saus tiram, garam, dan merica\n6. Larutkan maizena lalu tuang agar kuah mengental\n7. Sajikan hangat\n8. Selesai. Silahkan dinikmati!', 20, 3, 'Mudah', 'Sayuran', 'https://source.unsplash.com/500x400/?capcay', 210, 10.0, 22.0, 9.0, '2026-02-01 12:16:50'),
(23, 'Tempe Goreng Tepung', 'Tempe renyah dengan balutan tepung berbumbu', 'Tempe 1 papan, tepung terigu 150 gram, bawang putih 2 siung, ketumbar, garam, air, minyak', '1. Iris tempe tipis-tipis\n2. Haluskan bawang putih, ketumbar, dan garam\n3. Campur bumbu dengan tepung dan air menjadi adonan\n4. Celupkan tempe ke adonan\n5. Goreng dalam minyak panas hingga kuning keemasan\n6. Tiriskan dan sajikan\n7. Selesai. Silahkan dinikmati!', 15, 3, 'Mudah', 'Snack', 'https://source.unsplash.com/500x400/?tempe-goreng', 300, 14.0, 28.0, 18.0, '2026-02-01 12:16:50'),
(24, 'Es Teh Manis Segar', 'Minuman teh dingin manis menyegarkan', 'Teh celup 2 kantong, gula 3 sdm, air panas 500 ml, es batu secukupnya', '1. Seduh teh dengan air panas selama 3-5 menit\n2. Tambahkan gula lalu aduk hingga larut\n3. Siapkan gelas berisi es batu\n4. Tuang teh manis ke dalam gelas\n5. Sajikan dingin\n6. Selesai. Silahkan dinikmati!', 5, 2, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?iced-tea', 120, 0.0, 30.0, 0.0, '2026-02-01 12:16:50'),
(25, 'Pancake Pisang', 'Pancake lembut dengan rasa manis alami pisang', 'Tepung terigu 150 gram, susu 200 ml, telur 1 butir, gula 2 sdm, pisang matang 2 buah, baking powder 1 sdt, mentega', '1. Haluskan pisang dengan garpu\n2. Campur tepung, gula, dan baking powder\n3. Tambahkan susu, telur, dan pisang lalu aduk rata\n4. Panaskan teflon dan oles mentega\n5. Tuang adonan dan masak hingga muncul gelembung\n6. Balik dan masak sisi lainnya\n7. Sajikan hangat dengan madu atau sirup\n8. Selesai. Silahkan dinikmati!', 20, 3, 'Mudah', 'Dessert', 'https://source.unsplash.com/500x400/?pancake', 350, 8.0, 58.0, 10.0, '2026-02-01 12:16:50'),
(26, 'Soto Ayam Kuning', 'Soto ayam berkuah kuning segar dengan suwiran ayam dan bihun', 'Ayam 500 gram, serai 2 batang, daun salam 2 lembar, kunyit, bawang merah 6 siung, bawang putih 4 siung, bihun, kol, daun bawang, garam', '1. Rebus ayam hingga empuk lalu suwir-suwir\n2. Haluskan bumbu lalu tumis hingga harum\n3. Masukkan serai dan daun salam\n4. Tuang air kaldu rebusan ayam\n5. Tambahkan ayam suwir dan bumbu\n6. Sajikan dengan bihun, kol, dan daun bawang\n7. Nikmati hangat\n8. Selesai. Silahkan dinikmati!', 45, 4, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?soto-ayam', 420, 35.0, 28.0, 20.0, '2026-02-01 12:16:50'),
(27, 'Bakwan Sayur', 'Gorengan renyah berisi sayuran yang cocok untuk camilan', 'Tepung terigu 200 gram, wortel, kol, daun bawang, bawang putih 2 siung, garam, merica, air, minyak', '1. Iris tipis semua sayuran\n2. Campur tepung, bumbu halus, dan air\n3. Masukkan sayuran ke adonan\n4. Panaskan minyak\n5. Sendok adonan lalu goreng hingga kecoklatan\n6. Tiriskan dan sajikan hangat\n7. Selesai. Silahkan dinikmati!', 20, 4, 'Mudah', 'Snack', 'https://source.unsplash.com/500x400/?bakwan', 270, 6.0, 32.0, 16.0, '2026-02-01 12:16:50'),
(28, 'Ikan Bakar Sambal Dabu', 'Ikan bakar dengan sambal segar khas Manado', 'Ikan nila 2 ekor, jeruk nipis, garam, tomat, bawang merah, cabai rawit, daun bawang, minyak', '1. Bersihkan ikan lalu lumuri jeruk nipis dan garam\n2. Bakar ikan hingga matang sambil dibalik\n3. Iris semua bahan sambal\n4. Campur sambal dengan minyak panas dan garam\n5. Sajikan ikan bakar dengan sambal dabu segar\n6. Selesai. Silahkan dinikmati!', 30, 3, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?ikan-bakar', 390, 40.0, 6.0, 22.0, '2026-02-01 12:16:50'),
(29, 'Nugget Ayam Homemade', 'Nugget ayam lembut buatan sendiri tanpa pengawet', 'Dada ayam 300 gram, tepung roti, tepung terigu, telur 1 butir, bawang putih, garam, merica, minyak', '1. Haluskan ayam bersama bawang putih dan bumbu\n2. Campur dengan tepung terigu dan telur\n3. Kukus adonan hingga matang\n4. Potong sesuai bentuk\n5. Celupkan ke telur lalu balur tepung roti\n6. Goreng hingga keemasan\n7. Sajikan dengan saus\n8. Selesai. Silahkan dinikmati!', 40, 5, 'Sedang', 'Snack', 'https://source.unsplash.com/500x400/?chicken-nugget', 450, 28.0, 30.0, 25.0, '2026-02-01 12:16:50'),
(30, 'Jus Mangga Segar', 'Minuman jus mangga manis alami dan menyegarkan', 'Mangga matang 2 buah, gula cair 2 sdm, susu kental manis 1 sdm, air dingin, es batu', '1. Kupas dan potong mangga\n2. Masukkan ke blender bersama air dan gula\n3. Blender hingga halus\n4. Tambahkan es batu dan susu kental manis\n5. Blender sebentar lalu sajikan dingin\n6. Selesai. Silahkan dinikmati!', 7, 2, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?mango-juice', 180, 2.0, 42.0, 1.0, '2026-02-01 12:16:50'),
(31, 'Lontong Sayur Padang', 'Lontong dengan kuah santan labu siam khas Padang', 'Lontong, labu siam, kacang panjang, santan 700 ml, bawang merah 6 siung, bawang putih 4 siung, cabai merah, serai, daun salam, garam', '1. Tumis bumbu halus hingga harum\n2. Masukkan serai dan daun salam\n3. Tambahkan labu siam dan kacang panjang\n4. Tuang santan sambil diaduk agar tidak pecah\n5. Masak hingga sayur empuk dan kuah mengental\n6. Potong lontong\n7. Siram kuah dan sajikan hangat\n8. Selesai. Silahkan dinikmati!', 35, 4, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?lontong-sayur', 390, 9.0, 48.0, 18.0, '2026-02-01 12:16:50'),
(32, 'Urap Sayur Jawa', 'Sayuran rebus dengan kelapa parut berbumbu', 'Bayam, tauge, kacang panjang, kelapa parut 150 gram, bawang putih, kencur, cabai, gula merah, garam', '1. Rebus semua sayuran hingga matang lalu tiriskan\n2. Kukus kelapa parut sebentar\n3. Haluskan bumbu\n4. Campurkan bumbu dengan kelapa\n5. Aduk kelapa dengan sayuran\n6. Sajikan segar\n7. Selesai. Silahkan dinikmati!', 20, 3, 'Mudah', 'Sayuran', 'https://source.unsplash.com/500x400/?urap', 180, 6.0, 18.0, 9.0, '2026-02-01 12:16:50'),
(33, 'Tahu Crispy', 'Tahu goreng renyah dengan lapisan tepung berbumbu', 'Tahu putih 10 potong, tepung terigu 150 gram, tepung maizena 2 sdm, bawang putih bubuk, garam, merica, air, minyak', '1. Potong tahu sesuai selera\n2. Campur semua bahan tepung dan bumbu\n3. Tambahkan air hingga adonan agak kental\n4. Celupkan tahu ke adonan\n5. Goreng dalam minyak panas hingga renyah\n6. Tiriskan dan sajikan dengan cabai rawit\n7. Selesai. Silahkan dinikmati!', 15, 5, 'Mudah', 'Snack', 'https://source.unsplash.com/500x400/?fried-tofu', 280, 10.0, 24.0, 18.0, '2026-02-01 12:16:50'),
(34, 'Es Jeruk Peras', 'Minuman jeruk segar kaya vitamin C', 'Jeruk peras 4 buah, gula cair 3 sdm, air dingin 300 ml, es batu secukupnya', '1. Peras jeruk dan saring bijinya\n2. Campurkan gula cair dan air dingin\n3. Aduk hingga rata\n4. Tambahkan es batu\n5. Sajikan segera selagi dingin\n6. Selesai. Silahkan dinikmati!', 5, 2, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?orange-juice', 110, 1.0, 26.0, 0.0, '2026-02-01 12:16:50'),
(35, 'Kue Lumpur Kentang', 'Kue tradisional lembut dengan aroma santan dan vanila', 'Kentang kukus 250 gram, tepung terigu 100 gram, santan 200 ml, gula 100 gram, telur 2 butir, vanila, kismis, margarin', '1. Haluskan kentang kukus\n2. Campur semua bahan kecuali kismis\n3. Aduk hingga adonan halus\n4. Panaskan cetakan dan oles margarin\n5. Tuang adonan ke cetakan\n6. Tambahkan kismis di atasnya\n7. Masak hingga matang lalu angkat\n8. Selesai. Silahkan dinikmati!', 30, 5, 'Sedang', 'Dessert', 'https://source.unsplash.com/500x400/?kue-tradisional', 360, 6.0, 55.0, 12.0, '2026-02-01 12:16:50'),
(36, 'Soto Kudus', 'Soto ayam bening khas Kudus dengan suwiran ayam kampung', 'Ayam kampung, bawang putih, bawang merah, jahe, merica, daun seledri, tauge, bihun', '1. Rebus ayam hingga empuk\n2. Haluskan dan tumis bumbu\n3. Masukkan ke kuah kaldu\n4. Suwir ayam\n5. Siapkan mangkuk berisi bihun dan tauge\n6. Tuang kuah dan ayam\n7. Taburi seledri dan bawang goreng\n8. Selesai. Silahkan dinikmati!', 45, 3, 'Sedang', 'Sup', 'https://source.unsplash.com/500x400/?soto', 310, 28.0, 20.0, 12.0, '2026-02-01 12:16:50'),
(37, 'Plecing Kangkung Lombok', 'Kangkung rebus dengan sambal tomat pedas', 'Kangkung 1 ikat, tomat 2 buah, cabai rawit 10 buah, terasi, bawang putih, garam, jeruk limau', '1. Rebus kangkung sebentar lalu tiriskan\n2. Ulek semua bahan sambal\n3. Peras jeruk limau\n4. Tata kangkung di piring\n5. Siram sambal di atasnya\n6. Sajikan segar pedas\n7. Selesai. Silahkan dinikmati!', 10, 2, 'Mudah', 'Sayuran', 'https://source.unsplash.com/500x400/?kangkung-sambal', 140, 4.0, 10.0, 7.0, '2026-02-01 12:16:50'),
(38, 'Tempe Mendoan', 'Tempe goreng tipis setengah matang khas Banyumas', 'Tempe tipis 10 lembar, tepung terigu 150 gram, tepung beras 2 sdm, daun bawang, ketumbar bubuk, bawang putih, garam, air, minyak', '1. Campur tepung terigu, tepung beras, dan bumbu halus\n2. Tambahkan air hingga adonan encer\n3. Masukkan irisan daun bawang\n4. Panaskan minyak banyak\n5. Celupkan tempe ke adonan\n6. Goreng sebentar hingga setengah matang (tidak terlalu kering)\n7. Angkat dan tiriskan\n8. Sajikan hangat dengan sambal kecap\n9. Selesai. Silahkan dinikmati!', 15, 4, 'Mudah', 'Snack', 'https://source.unsplash.com/500x400/?tempe-goreng', 300, 14.0, 22.0, 20.0, '2026-02-01 12:16:50'),
(39, 'Wedang Jahe Gula Aren', 'Minuman tradisional hangat dari jahe bakar dan gula aren yang menghangatkan tubuh', 'Jahe 100 gram, gula aren 80 gram, serai 1 batang, daun pandan 1 lembar, air 800 ml, sedikit garam', '1. Cuci bersih jahe lalu memarkan atau geprek agar aromanya keluar.\n2. Bakar jahe sebentar di atas api atau teflon hingga harum untuk memberi aroma smoky khas wedang.\n3. Didihkan air di dalam panci.\n4. Masukkan jahe bakar, serai yang dimemarkan, dan daun pandan yang disimpulkan.\n5. Rebus selama 10 sampai 15 menit sampai air berubah warna kecoklatan dan harum.\n6. Tambahkan gula aren yang sudah disisir halus agar cepat larut.\n7. Aduk hingga gula larut sempurna dan rasa manis merata.\n8. Tambahkan sedikit garam untuk menyeimbangkan rasa.\n9. Saring ke dalam gelas saji.\n10. Sajikan hangat, cocok diminum saat hujan atau malam hari.\n11. Selesai. Silahkan dinikmati!', 15, 2, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?ginger-tea', 120, 0.0, 28.0, 0.0, '2026-02-01 12:16:50'),
(40, 'Nasi Tempong Banyuwangi', 'Nasi putih dengan aneka lauk goreng dan sambal super pedas khas Banyuwangi', 'Nasi putih 4 porsi, ayam goreng 2 potong, tahu goreng 2 buah, tempe goreng 2 potong, daun kemangi, mentimun, kol rebus, cabai rawit 10 buah, cabai merah 3 buah, terasi 1 sdt, tomat 1 buah, garam, gula, jeruk limau', '1. Siapkan nasi putih hangat sebagai dasar sajian.\n2. Goreng ayam, tahu, dan tempe hingga matang kecoklatan lalu tiriskan minyaknya.\n3. Cuci bersih kemangi, mentimun, dan kol, potong sesuai selera sebagai lalapan segar.\n4. Untuk sambal, rebus sebentar cabai merah dan tomat agar tidak terlalu langu.\n5. Ulek cabai rawit, cabai merah, terasi bakar, tomat, garam, dan sedikit gula sampai halus kasar.\n6. Tambahkan perasan jeruk limau agar rasa segar dan pedasnya lebih nendang.\n7. Koreksi rasa sesuai selera (asin, pedas, asam, manis).\n8. Tata nasi di piring, susun lauk goreng dan lalapan di sekelilingnya.\n9. Letakkan sambal tempong di atas atau samping nasi.\n10. Sajikan segera selagi hangat.\n11. Selesai. Silahkan dinikmati!', 30, 4, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?nasi-traditional-indonesian', 520, 28.0, 62.0, 18.0, '2026-02-01 12:16:50'),
(41, 'Seblak Bandung', 'Seblak pedas gurih dengan kerupuk kenyal khas Bandung', 'Kerupuk bawang 100 gram, makaroni 50 gram, telur 1 butir, bakso 5 buah, sawi, bawang putih 3 siung, kencur 2 cm, cabai rawit 8 buah, garam, gula, minyak', '1. Rendam kerupuk hingga lunak lalu tiriskan\n2. Haluskan bawang putih, cabai, dan kencur\n3. Tumis bumbu halus hingga harum\n4. Masukkan telur lalu orak-arik\n5. Tambahkan bakso dan makaroni\n6. Tuang sedikit air kemudian masukkan kerupuk\n7. Tambahkan sawi dan bumbu\n8. Masak hingga kuah menyusut dan sajikan panas\n9. Selesai. Silahkan dinikmati!', 20, 2, 'Mudah', 'Snack', 'https://source.unsplash.com/500x400/?seblak', 420, 12.0, 60.0, 18.0, '2026-02-01 12:16:50'),
(42, 'Siomay Bandung', 'Siomay ikan kukus dengan bumbu kacang', 'Ikan tenggiri 300 gram, tepung sagu, telur, pare, kol, kentang, kacang tanah, bawang putih', '1. Campur ikan giling dengan bumbu dan sagu\n2. Bentuk siomay\n3. Kukus hingga matang\n4. Rebus sayuran pelengkap\n5. Haluskan kacang goreng dan bumbu\n6. Sajikan siomay dengan saus kacang\n7. Selesai. Silahkan dinikmati!', 50, 4, 'Sedang', 'Snack', 'https://source.unsplash.com/500x400/?siomay', 380, 20.0, 38.0, 14.0, '2026-02-01 12:16:50'),
(43, 'Sup Jagung Telur', 'Sup sederhana hangat dengan rasa manis gurih', 'Jagung manis pipil 2 buah, telur 2 butir, bawang putih 2 siung, daun bawang, kaldu ayam, garam, merica, maizena', '1. Rebus air bersama jagung hingga empuk\n2. Tumis bawang putih lalu masukkan ke kuah\n3. Tambahkan kaldu dan bumbu\n4. Larutkan maizena untuk mengentalkan\n5. Kocok telur lalu tuang perlahan sambil diaduk\n6. Taburi daun bawang\n7. Sajikan hangat\n8. Selesai. Silahkan dinikmati!', 15, 3, 'Mudah', 'Sup', 'https://source.unsplash.com/500x400/?corn-soup', 210, 8.0, 30.0, 6.0, '2026-02-01 12:16:50'),
(44, 'Roti Bakar Coklat Keju', 'Roti bakar renyah dengan isian coklat dan keju lumer', 'Roti tawar 4 lembar, margarin, meses coklat, keju parut, susu kental manis', '1. Oles kedua sisi roti dengan margarin\n2. Panggang di teflon hingga kecoklatan\n3. Tambahkan meses dan keju parut\n4. Beri susu kental manis\n5. Tutup dengan roti lainnya\n6. Panggang sebentar hingga lumer\n7. Potong dan sajikan hangat\n8. Selesai. Silahkan dinikmati!', 10, 2, 'Mudah', 'Sarapan', 'https://source.unsplash.com/500x400/?toast-bread', 450, 14.0, 55.0, 24.0, '2026-02-01 12:16:50'),
(45, 'Jus Alpukat Coklat', 'Minuman jus alpukat lembut dengan sirup coklat manis', 'Alpukat matang 2 buah, susu kental manis 3 sdm, gula 1 sdm, air matang 200 ml, es batu, sirup coklat', '1. Kerok daging alpukat dan masukkan ke blender\n2. Tambahkan susu, gula, air, dan es batu\n3. Blender hingga halus dan lembut\n4. Tuang sirup coklat ke gelas\n5. Masukkan jus alpukat\n6. Sajikan dingin\n7. Selesai. Silahkan dinikmati!', 5, 2, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?avocado-juice', 320, 6.0, 28.0, 22.0, '2026-02-01 12:16:50'),
(46, 'Bakso Kuah Sederhana', 'Bakso sapi dengan kuah kaldu hangat dan gurih', 'Bakso sapi 15 butir, mie kuning, sawi hijau, bawang putih 4 siung, merica, garam, kaldu sapi, daun bawang, bawang goreng', '1. Rebus air hingga mendidih\n2. Haluskan bawang putih lalu tumis hingga harum\n3. Masukkan tumisan ke air rebusan\n4. Tambahkan bakso dan kaldu\n5. Masukkan mie dan sawi hingga matang\n6. Koreksi rasa dengan garam dan merica\n7. Sajikan dengan taburan daun bawang dan bawang goreng\n8. Selesai. Silahkan dinikmati!', 25, 3, 'Mudah', 'Sup', 'https://source.unsplash.com/500x400/?bakso', 480, 22.0, 52.0, 20.0, '2026-02-01 12:16:50'),
(47, 'Tahu Gejrot Cirebon', 'Tahu goreng dengan kuah gula asam pedas', 'Tahu pong, gula merah, asam jawa, bawang merah, cabai rawit, bawang putih, garam', '1. Goreng tahu hingga kopong\n2. Rebus gula merah dan asam jawa\n3. Ulek bawang dan cabai\n4. Campur dengan kuah gula\n5. Potong tahu\n6. Siram kuah di atasnya\n7. Sajikan hangat\n8. Selesai. Silahkan dinikmati!', 15, 3, 'Mudah', 'Snack', 'https://source.unsplash.com/500x400/?tahu-gejrot', 250, 8.0, 28.0, 12.0, '2026-02-01 12:16:50'),
(48, 'Nasi Kuning Rice Cooker', 'Nasi kuning praktis gurih untuk sarapan atau acara', 'Beras 500 gram, santan 500 ml, kunyit halus 1 sdt, daun salam, serai, garam', '1. Cuci beras hingga bersih\n2. Campur santan, kunyit, garam, dan rempah\n3. Masukkan beras ke rice cooker\n4. Tuang campuran santan\n5. Aduk rata lalu masak hingga matang\n6. Aduk kembali agar pulen\n7. Sajikan dengan lauk pelengkap\n8. Selesai. Silahkan dinikmati!', 30, 4, 'Mudah', 'Makanan Utama', 'https://source.unsplash.com/500x400/?nasi-kuning', 400, 8.0, 65.0, 12.0, '2026-02-01 12:16:50'),
(49, 'Puding Coklat Susu', 'Puding lembut manis rasa coklat disukai anak-anak', 'Agar-agar bubuk coklat 1 sachet, susu cair 500 ml, gula 4 sdm, coklat bubuk 1 sdm, air 200 ml', '1. Campur semua bahan dalam panci\n2. Aduk hingga rata dan tidak menggumpal\n3. Masak sambil diaduk hingga mendidih\n4. Tuang ke cetakan\n5. Dinginkan hingga mengeras\n6. Simpan di kulkas agar lebih segar\n7. Sajikan dingin\n8. Selesai. Silahkan dinikmati!', 15, 5, 'Mudah', 'Dessert', 'https://source.unsplash.com/500x400/?chocolate-pudding', 220, 4.0, 38.0, 6.0, '2026-02-01 12:16:50'),
(50, 'Teh Tarik', 'Minuman teh susu khas dengan busa lembut', 'Teh hitam 2 sdm, susu kental manis 3 sdm, gula 1 sdm, air panas 250 ml', '1. Seduh teh dengan air panas hingga pekat\n2. Saring ke dalam gelas besar\n3. Tambahkan susu dan gula\n4. Aduk rata\n5. Tuang bolak-balik antara dua gelas hingga berbusa\n6. Sajikan hangat atau dengan es\n7. Selesai. Silahkan dinikmati!', 5, 2, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?teh-tarik', 180, 3.0, 30.0, 6.0, '2026-02-01 12:16:50'),
(51, 'Nasi Liwet Solo', 'Nasi gurih santan dengan ayam suwir dan labu siam', 'Beras, santan 600 ml, daun salam, serai, ayam suwir, labu siam, telur pindang', '1. Masak nasi dengan santan dan rempah\n2. Tumis labu siam berbumbu\n3. Siapkan ayam suwir\n4. Kukus nasi hingga matang\n5. Sajikan dengan lauk pelengkap\n6. Selesai. Silahkan dinikmati!', 40, 4, 'Mudah', 'Makanan Utama', 'https://source.unsplash.com/500x400/?nasi-liwet', 430, 20.0, 55.0, 16.0, '2026-02-01 12:16:50'),
(52, 'Gulai Daun Singkong Tumbuk', 'Gulai khas Minang dengan daun singkong lembut dan santan gurih', 'Daun singkong 2 ikat, santan 700 ml, cabai merah, bawang merah, bawang putih, lengkuas, serai, daun kunyit, garam', '1. Rebus daun singkong hingga empuk lalu tumbuk kasar\n2. Haluskan cabai, bawang, dan bumbu\n3. Tumis bumbu sampai harum\n4. Masukkan serai dan daun kunyit\n5. Tuang santan sambil diaduk\n6. Masukkan daun singkong tumbuk\n7. Masak hingga kuah mengental dan bumbu meresap\n8. Sajikan hangat dengan nasi putih\n9. Selesai. Silahkan dinikmati!', 30, 4, 'Sedang', 'Sayuran', 'https://source.unsplash.com/500x400/?gulai', 300, 7.0, 18.0, 20.0, '2026-02-01 12:16:50'),
(53, 'Nasi Tutug Oncom', 'Nasi hangat yang diaduk dengan oncom bakar berbumbu khas Sunda dengan aroma smoky gurih', 'Beras 400 gram, oncom merah 200 gram, bawang merah 5 siung, bawang putih 3 siung, cabai merah 3 buah, kencur 1 cm, daun kemangi segenggam, garam, gula, minyak', '1. Cuci beras lalu masak menjadi nasi putih hingga matang dan pulen, sisihkan tetap hangat.\n2. Bakar oncom di atas api kecil atau teflon sampai agak kering dan aromanya keluar, kemudian hancurkan kasar dengan garpu.\n3. Haluskan bawang merah, bawang putih, cabai, kencur, garam, dan sedikit gula.\n4. Tumis bumbu halus dengan sedikit minyak sampai benar-benar harum dan matang supaya tidak langu.\n5. Masukkan oncom yang sudah dihancurkan ke dalam tumisan, aduk rata hingga bumbu meresap dan agak kering.\n6. Koreksi rasa, tambahkan garam/gula bila perlu.\n7. Siapkan wadah besar, campurkan nasi panas dengan oncom berbumbu sedikit demi sedikit sambil diaduk hingga tercampur merata.\n8. Tambahkan daun kemangi segar, aduk ringan.\n9. Sajikan hangat bersama lalap, tahu/tempe goreng, dan sambal.\n10. Selesai. Silahkan dinikmati!', 25, 3, 'Mudah', 'Makanan Utama', 'https://source.unsplash.com/500x400/?nasi-sunda', 420, 12.0, 65.0, 11.0, '2026-02-01 12:16:50'),
(54, 'Es Cendol Gula Aren', 'Minuman manis segar dengan santan dan gula aren', 'Cendol 200 gram, santan 400 ml, gula aren 150 gram, daun pandan, es batu', '1. Rebus gula aren dengan sedikit air dan pandan hingga larut\n2. Dinginkan sirup gula\n3. Siapkan santan matang\n4. Susun cendol dan es batu dalam gelas\n5. Tuang santan dan sirup gula\n6. Aduk sebelum diminum\n7. Selesai. Silahkan dinikmati!', 10, 3, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?cendol', 260, 3.0, 45.0, 8.0, '2026-02-01 12:16:50'),
(55, 'Telur Dadar Padang', 'Telur dadar tebal dengan daun bawang dan rempah', 'Telur 4 butir, daun bawang, daun kunyit, bawang merah, cabai merah, tepung beras 1 sdm, garam, minyak', '1. Iris semua bumbu dan daun\n2. Kocok telur bersama bumbu dan tepung\n3. Panaskan minyak agak banyak\n4. Tuang adonan telur\n5. Goreng dengan api sedang hingga tebal dan matang\n6. Balik sekali lalu angkat\n7. Potong dan sajikan\n8. Selesai. Silahkan dinikmati!', 12, 3, 'Mudah', 'Lauk', 'https://source.unsplash.com/500x400/?omelette', 340, 22.0, 6.0, 26.0, '2026-02-01 12:16:50'),
(56, 'Dadar Gulung Pandan', 'Kue dadar gulung hijau lembut berisi kelapa parut manis gula merah khas jajanan pasar', 'Tepung terigu 200 gram, telur 1 butir, santan 400 ml, air pandan atau pasta pandan, garam sejumput, minyak untuk olesan, kelapa parut 200 gram, gula merah 150 gram, daun pandan 2 lembar, air 50 ml', '1. Campur kelapa parut dengan sedikit garam lalu kukus 10 menit agar tidak cepat basi\n2. Iris halus gula merah lalu masak bersama air dan daun pandan hingga larut dan mengental\n3. Masukkan kelapa kukus ke larutan gula merah, aduk hingga tercampur rata dan agak kering\n4. Masak sampai isian legit dan tidak berair lalu dinginkan\n5. Dalam wadah lain campurkan tepung terigu, telur, santan, dan garam\n6. Tambahkan air pandan atau pasta pandan sedikit demi sedikit sampai adonan berwarna hijau dan harum\n7. Aduk menggunakan whisk sampai adonan halus tanpa gumpalan\n8. Saring adonan agar teksturnya benar-benar lembut\n9. Panaskan teflon datar anti lengket dengan api kecil lalu oles tipis minyak\n10. Tuang satu sendok sayur adonan, putar teflon hingga membentuk kulit tipis seperti crepe\n11. Masak sampai permukaan matang dan tidak lengket, tidak perlu dibalik\n12. Angkat kulit dadar dan letakkan di piring datar\n13. Ambil satu sendok isian kelapa, taruh di bagian tengah kulit\n14. Lipat sisi kiri dan kanan lalu gulung rapat ke depan seperti lumpia\n15. Ulangi hingga adonan habis\n16. Sajikan dadar gulung dalam keadaan dingin atau suhu ruang\n17. Selesai. Silahkan dinikmati!', 40, 4, 'Mudah', 'Dessert', 'https://source.unsplash.com/500x400/?dadar-gulung', 280, 5.0, 48.0, 9.0, '2026-02-01 12:16:50'),
(57, 'Kwetiau Goreng Seafood', 'Kwetiau goreng dengan udang dan cumi gurih', 'Kwetiau basah 300 gram, udang, cumi, telur 1 butir, bawang putih, kecap manis, saus tiram, sawi, minyak', '1. Tumis bawang putih hingga harum\n2. Masukkan seafood dan masak hingga berubah warna\n3. Tambahkan telur lalu orak-arik\n4. Masukkan kwetiau dan sayuran\n5. Bumbui kecap dan saus tiram\n6. Aduk hingga matang merata\n7. Sajikan panas\n8. Selesai. Silahkan dinikmati!', 20, 3, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?kwetiau', 540, 24.0, 68.0, 18.0, '2026-02-01 12:16:50'),
(58, 'Kue Lupis Ketan', 'Jajanan tradisional dari beras ketan dengan parutan kelapa dan siraman gula merah cair yang manis legit', 'Beras ketan 500 gram, daun pisang secukupnya, kelapa parut 1/2 butir, garam 1/2 sdt, gula merah 200 gram, gula pasir 2 sdm, daun pandan 1 lembar, air secukupnya', '1. Rendam beras ketan minimal 3 sampai 4 jam agar empuk lalu tiriskan\n2. Siapkan daun pisang, bentuk kerucut atau segitiga, isi dengan ketan secukupnya\n3. Lipat dan semat dengan lidi agar tidak terbuka\n4. Rebus lupis dalam air mendidih selama 1,5 sampai 2 jam hingga matang\n5. Angkat dan tiriskan, biarkan agak dingin\n6. Campur kelapa parut dengan sedikit garam lalu kukus 10 menit agar tahan lama\n7. Rebus gula merah, gula pasir, daun pandan, dan sedikit air hingga larut dan mengental, saring\n8. Buka daun pisang, potong lupis, gulingkan ke kelapa parut\n9. Siram saus gula merah di atasnya\n10. Sajikan sebagai camilan tradisional\n11. Selesai. Silahkan dinikmati!', 120, 5, 'Mudah', 'Snack', 'https://source.unsplash.com/500x400/?lupis-ketan', 210, 4.0, 46.0, 3.0, '2026-02-01 12:16:50'),
(59, 'Ayam Goreng Kremes', 'Ayam goreng renyah dengan kremesan gurih', 'Ayam 1 ekor, bawang putih, ketumbar, kunyit, garam, tepung beras 3 sdm, air kaldu, minyak', '1. Haluskan bumbu lalu lumuri ayam\n2. Rebus ayam hingga empuk sambil meresap bumbu\n3. Goreng ayam hingga kecoklatan\n4. Campur tepung beras dengan sisa kaldu\n5. Tuang adonan kremes ke minyak panas hingga berserabut\n6. Tiriskan kremesan\n7. Sajikan ayam dengan kremes\n8. Selesai. Silahkan dinikmati!', 45, 4, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?fried-chicken', 560, 32.0, 10.0, 38.0, '2026-02-01 12:16:50'),
(60, 'Smoothie Mangga Yogurt', 'Minuman sehat segar perpaduan mangga dan yogurt', 'Mangga matang 1 buah, yogurt plain 150 ml, madu 1 sdm, es batu secukupnya', '1. Kupas dan potong mangga\n2. Masukkan semua bahan ke blender\n3. Blender hingga halus\n4. Cicipi dan sesuaikan manisnya\n5. Tuang ke gelas\n6. Sajikan dingin\n7. Selesai. Silahkan dinikmati!', 5, 2, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?mango-smoothie', 190, 5.0, 32.0, 3.0, '2026-02-01 12:16:50'),
(61, 'Gudeg Jogja', 'Olahan nangka muda manis gurih khas Yogyakarta', 'Nangka muda 500 gram, santan 800 ml, gula merah 150 gram, bawang merah 6 siung, bawang putih 4 siung, ketumbar, daun salam, lengkuas, garam', '1. Potong nangka muda lalu rebus hingga empuk\n2. Haluskan bawang dan ketumbar lalu tumis hingga harum\n3. Masukkan nangka, daun salam, lengkuas\n4. Tambahkan santan dan gula merah\n5. Masak dengan api kecil sambil diaduk sesekali\n6. Masak hingga kuah menyusut dan bumbu meresap\n7. Sajikan dengan nasi, telur, dan ayam opor\n8. Selesai. Silahkan dinikmati!', 180, 6, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?gudeg', 420, 10.0, 55.0, 18.0, '2026-02-01 12:16:50'),
(62, 'Opor Ayam Kampung', 'Ayam kuah santan gurih dengan rempah tradisional', 'Ayam kampung 1 ekor, santan 700 ml, serai, daun salam, lengkuas, bawang merah 8 siung, bawang putih 5 siung, ketumbar, kemiri, garam', '1. Rebus ayam hingga setengah empuk\n2. Haluskan semua bumbu lalu tumis hingga harum\n3. Masukkan bumbu ke dalam rebusan ayam\n4. Tambahkan santan dan rempah daun\n5. Masak dengan api kecil agar santan tidak pecah\n6. Koreksi rasa hingga gurih\n7. Sajikan hangat\n8. Selesai. Silahkan dinikmati!', 60, 5, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?opor-ayam', 460, 32.0, 8.0, 36.0, '2026-02-01 12:16:50'),
(63, 'Kue Putri Salju', 'Kue kering lembut bertabur gula halus dengan rasa manis gurih khas sajian Lebaran', 'Tepung terigu 250 gram, margarin 200 gram, gula halus 80 gram, kuning telur 2 butir, susu bubuk 2 sdm, keju parut 50 gram, gula halus tambahan untuk taburan', '1. Siapkan semua bahan dalam suhu ruang agar mudah tercampur\n2. Kocok margarin dan gula halus menggunakan mixer hingga lembut dan pucat\n3. Masukkan kuning telur satu per satu sambil terus dikocok rata\n4. Tambahkan susu bubuk dan keju parut, aduk perlahan\n5. Masukkan tepung terigu sedikit demi sedikit sambil diayak\n6. Aduk menggunakan spatula sampai adonan kalis dan bisa dipulung\n7. Gilas adonan setebal kurang lebih 1 cm di atas meja yang ditaburi tepung\n8. Cetak bentuk bulan sabit atau sesuai selera\n9. Susun di loyang yang sudah dialasi kertas baking\n10. Panggang dalam oven 150°C selama 20–25 menit hingga matang tapi tidak kecoklatan\n11. Angkat dan biarkan hangat\n12. Gulingkan kue ke gula halus hingga terbalut merata\n13. Dinginkan sepenuhnya lalu simpan dalam toples kedap udara\n14. Selesai. Silahkan dinikmati!', 45, 5, 'Sedang', 'Dessert', 'https://source.unsplash.com/500x400/?putri-salju-cookies', 180, 3.0, 22.0, 10.0, '2026-02-01 12:16:50'),
(64, 'Es Cendol Dawet Ayu', 'Minuman tradisional khas Banjarnegara berisi cendol kenyal dengan santan gurih dan gula aren manis segar', 'Tepung beras 100 gram, tepung tapioka 50 gram, air pandan 600 ml, santan 500 ml, gula aren 200 gram, daun pandan 2 lembar, garam 1/2 sdt, es batu secukupnya', '1. Campur tepung beras dan tepung tapioka dalam wadah\n2. Tuang air pandan sedikit demi sedikit sambil diaduk hingga larut\n3. Masak adonan di api kecil sambil diaduk sampai mengental dan meletup\n4. Siapkan cetakan cendol dan baskom berisi air es\n5. Tekan adonan panas melalui cetakan hingga membentuk butiran\n6. Diamkan sampai cendol mengeras lalu tiriskan\n7. Rebus santan dengan daun pandan dan garam sambil diaduk agar tidak pecah lalu dinginkan\n8. Rebus gula aren dengan sedikit air sampai larut lalu saring\n9. Siapkan gelas, masukkan cendol, es batu, santan, dan sirup gula aren\n10. Aduk sebelum diminum dan sajikan dingin\n11. Selesai. Silahkan dinikmati!', 25, 5, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?cendol', 220, 2.0, 40.0, 6.0, '2026-02-01 12:16:50'),
(65, 'Serabi Solo', 'Kue tradisional lembut dengan santan manis', 'Tepung beras 200 gram, santan 400 ml, gula, ragi instan sedikit, daun pandan, topping gula merah', '1. Campur tepung, santan, gula, dan ragi\n2. Diamkan adonan 30 menit hingga mengembang\n3. Panaskan cetakan serabi\n4. Tuang adonan setengah cetakan\n5. Tutup hingga matang dan berpori\n6. Sajikan dengan kuah gula merah\n7. Selesai. Silahkan dinikmati!', 25, 6, 'Mudah', 'Dessert', 'https://source.unsplash.com/500x400/?serabi', 260, 6.0, 45.0, 6.0, '2026-02-01 12:16:50'),
(66, 'Papeda Ikan Kuah Kuning', 'Bubur sagu dengan kuah ikan rempah khas Papua', 'Tepung sagu 200 gram, ikan tongkol, kunyit, serai, daun jeruk, bawang merah, bawang putih, air, garam', '1. Seduh sagu dengan air panas sambil diaduk hingga mengental\n2. Rebus ikan hingga matang\n3. Tumis bumbu halus sampai harum\n4. Masukkan bumbu ke kuah ikan\n5. Tambahkan serai dan daun jeruk\n6. Masak hingga kuah kuning harum\n7. Sajikan papeda dengan kuah ikan\n8. Selesai. Silahkan dinikmati!', 40, 4, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?papeda', 300, 22.0, 38.0, 6.0, '2026-02-01 12:16:50'),
(67, 'Sambal Matah Bali', 'Sambal segar pedas wangi serai khas Bali', 'Bawang merah 8 siung, cabai rawit 8 buah, serai 2 batang, daun jeruk, terasi bakar, minyak panas, garam, jeruk limau', '1. Iris tipis semua bahan\n2. Campur dalam mangkuk\n3. Tambahkan garam dan perasan jeruk limau\n4. Panaskan minyak hingga sangat panas\n5. Siram minyak ke campuran sambal\n6. Aduk rata\n7. Sajikan sebagai pelengkap lauk\n8. Selesai. Silahkan dinikmati!', 10, 6, 'Mudah', 'Sambal', 'https://source.unsplash.com/500x400/?sambal', 120, 2.0, 8.0, 10.0, '2026-02-01 12:16:50'),
(68, 'Klepon Gula Merah', 'Kue bola ketan isi gula merah dengan kelapa parut', 'Tepung ketan 200 gram, air pandan, gula merah sisir, kelapa parut kukus, garam', '1. Campur tepung ketan dengan air pandan hingga kalis\n2. Ambil sedikit adonan dan isi gula merah\n3. Bentuk bulat kecil\n4. Rebus hingga mengapung\n5. Angkat dan tiriskan\n6. Gulingkan di kelapa parut\n7. Sajikan\n8. Selesai. Silahkan dinikmati!', 25, 6, 'Mudah', 'Dessert', 'https://source.unsplash.com/500x400/?klepon', 210, 3.0, 42.0, 4.0, '2026-02-01 12:16:50'),
(69, 'Ikan Bakar Jimbaran', 'Ikan bakar dengan bumbu khas Bali manis pedas', 'Ikan kakap 1 ekor, bawang merah, bawang putih, cabai merah, kemiri, terasi, kecap manis, jeruk nipis, minyak', '1. Bersihkan ikan dan lumuri jeruk nipis\n2. Haluskan bumbu lalu tumis sebentar\n3. Olesi ikan dengan bumbu\n4. Bakar sambil dibalik dan dioles sisa bumbu\n5. Bakar hingga matang dan harum\n6. Sajikan dengan sambal dan nasi hangat\n7. Selesai. Silahkan dinikmati!', 30, 3, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?ikan-bakar', 470, 38.0, 8.0, 30.0, '2026-02-01 12:16:50'),
(70, 'Es Pisang Ijo', 'Dessert khas Makassar dengan pisang balut adonan hijau dan kuah santan', 'Pisang raja 5 buah, tepung beras 150 gram, santan 400 ml, gula merah, daun pandan, sirup merah, es serut', '1. Campur tepung beras dan air pandan hingga kental\n2. Kukus pisang sebentar\n3. Bungkus pisang dengan adonan hijau lalu kukus kembali\n4. Rebus santan dengan gula dan pandan\n5. Potong pisang ijo\n6. Susun di mangkuk dengan es serut\n7. Siram kuah santan dan sirup lalu sajikan\n8. Selesai. Silahkan dinikmati!', 30, 4, 'Sedang', 'Dessert', 'https://source.unsplash.com/500x400/?es-pisang-ijo', 360, 6.0, 58.0, 8.0, '2026-02-01 12:16:50'),
(71, 'Ayam Penyet Surabaya', 'Ayam goreng empuk disajikan dengan sambal terasi pedas', 'Ayam 1 ekor, bawang putih, ketumbar, kunyit, garam, cabai rawit, terasi, tomat, minyak', '1. Haluskan bawang putih, ketumbar, kunyit, dan garam lalu lumuri ayam\n2. Rebus ayam sebentar hingga empuk\n3. Goreng ayam sampai keemasan\n4. Ulek cabai, terasi bakar, dan tomat untuk sambal\n5. Letakkan ayam di cobek lalu penyet hingga sedikit geprek\n6. Sajikan dengan nasi hangat dan lalapan\n7. Selesai. Silahkan dinikmati!', 35, 4, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?ayam-penyet', 520, 34.0, 10.0, 36.0, '2026-02-01 12:16:50'),
(72, 'Soto Banjar', 'Soto ayam kuah bening harum rempah khas Kalimantan', 'Ayam 1/2 ekor, kayu manis, cengkeh, pala, bawang merah, bawang putih, soun, telur rebus, garam', '1. Rebus ayam hingga matang lalu suwir\n2. Tumis bumbu halus dan rempah hingga harum\n3. Masukkan ke kaldu rebusan ayam\n4. Bumbui garam dan gula secukupnya\n5. Seduh soun dengan air panas\n6. Susun soun dan ayam di mangkuk\n7. Siram kuah panas dan sajikan\n8. Selesai. Silahkan dinikmati!', 40, 3, 'Sedang', 'Sup', 'https://source.unsplash.com/500x400/?soto-ayam', 330, 26.0, 24.0, 14.0, '2026-02-01 12:16:50'),
(73, 'Bakso Malang', 'Bakso daging sapi lengkap dengan mie dan pangsit', 'Daging sapi giling 500 gram, tepung tapioka 100 gram, bawang putih, garam, merica, mie kuning, pangsit goreng, sawi', '1. Campur daging, tepung, dan bumbu hingga kalis\n2. Bentuk bulatan bakso\n3. Rebus hingga mengapung\n4. Siapkan kuah kaldu panas\n5. Rebus mie dan sawi\n6. Tata mie, bakso, dan pangsit di mangkuk\n7. Siram kuah dan sajikan\n8. Selesai. Silahkan dinikmati!', 60, 5, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?bakso', 600, 38.0, 55.0, 28.0, '2026-02-01 12:16:50'),
(74, 'Pecel Madiun', 'Sayuran rebus dengan sambal kacang pedas manis', 'Bayam, tauge, kacang panjang, kol, kacang tanah goreng 200 gram, cabai, gula merah, bawang putih, asam jawa', '1. Rebus semua sayuran hingga matang lalu tiriskan\n2. Haluskan kacang tanah dan semua bumbu\n3. Tambahkan sedikit air hangat hingga jadi saus\n4. Susun sayuran di piring\n5. Siram sambal kacang di atasnya\n6. Sajikan dengan rempeyek atau nasi\n7. Selesai. Silahkan dinikmati!', 20, 3, 'Mudah', 'Sayuran', 'https://source.unsplash.com/500x400/?pecel', 350, 12.0, 40.0, 18.0, '2026-02-01 12:16:50'),
(75, 'Cireng Bandung', 'Aci goreng kenyal renyah khas Jawa Barat', 'Tepung tapioka 200 gram, bawang putih, daun bawang, garam, merica, air panas, minyak', '1. Campur tepung dengan bawang putih halus dan daun bawang\n2. Tuang air panas sedikit demi sedikit sambil diaduk\n3. Uleni hingga kalis\n4. Bentuk pipih sesuai selera\n5. Goreng dalam minyak panas hingga mengembang\n6. Tiriskan dan sajikan dengan saus sambal\n7. Selesai. Silahkan dinikmati!', 15, 5, 'Mudah', 'Snack', 'https://source.unsplash.com/500x400/?cireng', 280, 4.0, 45.0, 8.0, '2026-02-01 12:16:50'),
(76, 'Rujak Buah Serut', 'Rujak buah segar dengan sambal gula pedas', 'Nanas, mangga muda, bengkuang, pepaya muda, cabai rawit, gula merah, asam jawa, garam', '1. Kupas dan serut semua buah\n2. Ulek cabai, gula merah, garam, dan asam jawa\n3. Tambahkan sedikit air agar kental\n4. Campurkan buah dengan sambal\n5. Aduk rata\n6. Sajikan dingin\n7. Selesai. Silahkan dinikmati!', 10, 3, 'Mudah', 'Dessert', 'https://source.unsplash.com/500x400/?rujak-buah', 190, 3.0, 40.0, 2.0, '2026-02-01 12:16:50'),
(77, 'Nasi Kuning Tumpeng', 'Nasi kuning gurih untuk sajian spesial', 'Beras 500 gram, santan 600 ml, kunyit, serai, daun salam, garam', '1. Haluskan kunyit lalu campur dengan santan\n2. Masukkan beras, serai, dan daun salam\n3. Masak hingga air menyusut\n4. Kukus hingga matang\n5. Aduk agar pulen\n6. Cetak membentuk kerucut\n7. Sajikan dengan lauk pelengkap\n8. Selesai. Silahkan dinikmati!', 40, 6, 'Mudah', 'Makanan Utama', 'https://source.unsplash.com/500x400/?nasi-kuning', 420, 8.0, 60.0, 14.0, '2026-02-01 12:16:50');
INSERT INTO `resep` (`id`, `judul`, `deskripsi`, `bahan`, `langkah`, `waktu`, `porsi`, `tingkat_kesulitan`, `kategori`, `gambar_url`, `kalori`, `protein`, `karbohidrat`, `lemak`, `created_at`) VALUES
(78, 'Udang Balado Padang', 'Udang pedas merah khas Sumatera Barat', 'Udang 400 gram, cabai merah 10 buah, bawang merah 6 siung, bawang putih 3 siung, tomat, garam, gula, minyak', '1. Bersihkan udang lalu goreng sebentar\n2. Haluskan cabai dan bawang\n3. Tumis bumbu hingga harum dan matang\n4. Masukkan tomat dan bumbu penyedap\n5. Tambahkan udang\n6. Aduk hingga bumbu merata\n7. Sajikan panas\n8. Selesai. Silahkan dinikmati!', 25, 3, 'Sedang', 'Lauk', 'https://source.unsplash.com/500x400/?shrimp-spicy', 410, 32.0, 8.0, 28.0, '2026-02-01 12:16:50'),
(79, 'Karedok Sunda', 'Salad sayur mentah dengan bumbu kacang segar', 'Kacang panjang, kol, tauge, timun, terong kecil, kacang tanah, cabai, bawang putih, kencur, gula merah', '1. Iris tipis semua sayuran mentah\n2. Haluskan kacang tanah goreng dan bumbu\n3. Tambahkan air sedikit agar kental\n4. Campurkan sayuran dengan bumbu\n5. Aduk rata hingga terbalut\n6. Sajikan segera agar tetap segar\n7. Selesai. Silahkan dinikmati!', 15, 4, 'Mudah', 'Sayuran', 'https://source.unsplash.com/500x400/?karedok', 260, 10.0, 28.0, 12.0, '2026-02-01 12:16:50'),
(80, 'Es Doger Betawi', 'Minuman manis segar berisi tape dan kelapa muda', 'Santan 500 ml, gula merah, tape singkong, kelapa muda, roti tawar, sirup merah, es serut', '1. Rebus santan dan gula merah hingga larut lalu dinginkan\n2. Siapkan gelas saji\n3. Masukkan tape, kelapa muda, dan roti\n4. Tambahkan es serut\n5. Tuang santan manis dan sirup merah\n6. Aduk perlahan\n7. Sajikan dingin\n8. Selesai. Silahkan dinikmati!', 10, 4, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?es-doger', 340, 5.0, 55.0, 10.0, '2026-02-01 12:16:50'),
(81, 'Sop Buntut Jakarta', 'Sup buntut sapi berkuah bening gurih dengan sayuran', 'Buntut sapi 1 kg, wortel, kentang, tomat, bawang putih, bawang bombay, pala, lada, garam, seledri', '1. Rebus buntut hingga empuk dan buang kotoran\n2. Tumis bawang putih dan bawang bombay hingga harum\n3. Masukkan tumisan ke rebusan buntut\n4. Tambahkan wortel dan kentang\n5. Bumbui pala, lada, dan garam\n6. Masak hingga sayur matang\n7. Sajikan dengan taburan seledri dan bawang goreng\n8. Selesai. Silahkan dinikmati!', 120, 4, 'Sulit', 'Sup', 'https://source.unsplash.com/500x400/?sop-buntut', 520, 40.0, 18.0, 34.0, '2026-02-01 12:16:50'),
(82, 'Lontong Sayur Medan', 'Lontong dengan kuah santan labu siam dan telur', 'Lontong, labu siam, santan, telur rebus, tahu, kacang panjang, bawang merah, bawang putih, lengkuas, serai, daun salam', '1. Tumis bumbu halus hingga harum\n2. Masukkan labu siam dan kacang panjang\n3. Tambahkan santan dan rempah\n4. Masak hingga kuah mengental\n5. Potong lontong di mangkuk\n6. Siram kuah sayur dan beri telur serta tahu\n7. Sajikan hangat\n8. Selesai. Silahkan dinikmati!', 45, 4, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?lontong-sayur', 480, 14.0, 55.0, 24.0, '2026-02-01 12:16:50'),
(83, 'Tahu Tek Surabaya', 'Tahu goreng dengan lontong dan saus petis khas Jawa Timur', 'Tahu goreng, lontong, kentang, tauge, telur, petis udang, kacang tanah, bawang putih, cabai', '1. Goreng tahu dan kentang hingga matang\n2. Rebus tauge sebentar\n3. Haluskan kacang, petis, bawang putih, dan cabai\n4. Tambahkan air hangat hingga jadi saus\n5. Potong lontong dan tata semua bahan\n6. Siram saus petis\n7. Sajikan dengan kerupuk\n8. Selesai. Silahkan dinikmati!', 25, 3, 'Mudah', 'Snack', 'https://source.unsplash.com/500x400/?tahu-tek', 460, 18.0, 48.0, 22.0, '2026-02-01 12:16:50'),
(84, 'Sate Lilit Bali', 'Sate khas Bali dari daging cincang berbumbu rempah yang dililitkan pada serai lalu dibakar harum', 'Daging ayam cincang 400 gram, kelapa parut 100 gram, bawang merah 6 siung, bawang putih 4 siung, cabai merah 4 buah, ketumbar 1 sdt, lengkuas 2 cm, jahe 2 cm, serai batang untuk tusuk, daun jeruk, garam, gula, minyak', '1. Haluskan bawang merah, bawang putih, cabai, ketumbar, lengkuas, dan jahe\n2. Campurkan daging cincang dengan kelapa parut dan bumbu halus\n3. Tambahkan irisan daun jeruk, garam, dan gula lalu aduk rata\n4. Ambil sedikit adonan lalu lilitkan memanjang pada batang serai\n5. Padatkan agar tidak lepas saat dibakar\n6. Panaskan grill atau teflon, oles sedikit minyak\n7. Bakar sate sambil dibalik hingga matang dan harum kecoklatan\n8. Sajikan hangat dengan sambal matah atau nasi putih\n9. Selesai. Silahkan dinikmati!', 35, 4, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?sate-lilit-bali', 410, 30.0, 8.0, 28.0, '2026-02-01 12:16:50'),
(85, 'Pempek Kapal Selam', 'Pempek isi telur dengan kuah cuko pedas manis', 'Ikan tenggiri giling 300 gram, tepung sagu 200 gram, telur, bawang putih, garam, gula merah, asam jawa, cabai', '1. Campur ikan giling dan bumbu\n2. Tambahkan sagu dan uleni\n3. Bentuk adonan lalu isi telur\n4. Rebus hingga mengapung\n5. Goreng sebentar sebelum disajikan\n6. Rebus bahan cuko hingga larut\n7. Sajikan pempek dengan kuah cuko\n8. Selesai. Silahkan dinikmati!', 60, 4, 'Sedang', 'Snack', 'https://source.unsplash.com/500x400/?pempek', 400, 16.0, 52.0, 12.0, '2026-02-01 12:16:50'),
(86, 'Bubur Sagu Mutiara Ambon', 'Dessert khas Maluku berupa bubur lembut dari sagu mutiara dengan kuah santan manis gurih yang disajikan hangat atau dingin', 'Sagu mutiara 150 gram, air 1 liter, gula pasir 120 gram, santan 600 ml, daun pandan 2 lembar, garam 1/2 sdt, susu kental manis secukupnya, es batu opsional', '1. Rebus air hingga mendidih di panci besar\n2. Masukkan sagu mutiara lalu aduk agar tidak lengket di dasar panci\n3. Masak selama 15-20 menit hingga butiran sagu menjadi bening dan matang\n4. Tambahkan gula pasir lalu aduk sampai larut merata\n5. Masukkan daun pandan untuk memberi aroma harum\n6. Masak santan terpisah dengan sedikit garam sambil terus diaduk agar tidak pecah\n7. Setelah santan panas dan gurih, angkat lalu sisihkan\n8. Siapkan mangkuk saji, tuang sagu mutiara secukupnya\n9. Siram dengan kuah santan hangat di atasnya\n10. Tambahkan susu kental manis sesuai selera\n11. Bisa disajikan hangat atau tambahkan es batu jika ingin dingin\n12. Aduk sebelum dimakan agar rasa manis dan gurih tercampur rata\n13. Selesai. Silahkan dinikmati!', 25, 5, 'Mudah', 'Dessert', 'https://source.unsplash.com/500x400/?sago-porridge-dessert', 210, 3.0, 6.0, 42.0, '2026-02-01 12:16:50'),
(87, 'Klepon Pandan', 'Kue tradisional ketan isi gula merah dan kelapa parut', 'Tepung ketan 200 gram, air pandan, gula merah, kelapa parut, garam', '1. Campur tepung ketan dengan air pandan hingga kalis\n2. Ambil sedikit adonan, isi gula merah\n3. Bulatkan rapat\n4. Rebus hingga mengapung\n5. Angkat dan tiriskan\n6. Gulingkan di kelapa parut\n7. Sajikan\n8. Selesai. Silahkan dinikmati!', 20, 5, 'Mudah', 'Dessert', 'https://source.unsplash.com/500x400/?klepon', 220, 3.0, 40.0, 5.0, '2026-02-01 12:16:50'),
(88, 'Mi Aceh Goreng', 'Mi goreng pedas kari khas Aceh dengan daging', 'Mie kuning tebal, daging sapi, cabai, bawang merah, bawang putih, kari bubuk, kol, tomat, kecap', '1. Tumis bumbu halus hingga harum\n2. Masukkan daging dan masak hingga matang\n3. Tambahkan mie dan sedikit air\n4. Masukkan kol dan tomat\n5. Bumbui kari, garam, dan kecap\n6. Aduk hingga kering\n7. Sajikan panas\n8. Selesai. Silahkan dinikmati!', 25, 2, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?mie-goreng', 540, 26.0, 70.0, 20.0, '2026-02-01 12:16:50'),
(89, 'Bolu Kojo Palembang', 'Kue tradisional khas Palembang bertekstur lembut dan legit dengan aroma pandan serta santan yang gurih manis', 'Telur 5 butir, gula pasir 180 gram, tepung terigu 150 gram, santan kental 200 ml, margarin leleh 120 gram, air pandan 100 ml, susu kental manis 2 sdm, vanili 1/2 sdt, garam sejumput', '1. Kocok telur dan gula pasir menggunakan mixer hingga mengembang dan berwarna pucat\n2. Tambahkan vanili dan susu kental manis lalu aduk rata\n3. Masukkan tepung terigu sedikit demi sedikit sambil diayak agar tidak menggumpal\n4. Tuang santan, margarin leleh, dan air pandan lalu aduk perlahan sampai adonan tercampur rata\n5. Panaskan loyang dan olesi margarin tipis agar tidak lengket\n6. Tuang adonan ke dalam loyang hingga hampir penuh\n7. Panggang dalam oven suhu 170°C selama 35-40 menit hingga matang dan bagian atas kecoklatan\n8. Tes tusuk menggunakan lidi, jika tidak lengket berarti sudah matang\n9. Angkat dan dinginkan sebentar sebelum dipotong\n10. Potong bentuk wajik atau persegi sesuai ciri khas bolu kojo\n11. Sajikan sebagai camilan atau hidangan penutup\n12. Selesai. Silahkan dinikmati!', 45, 8, 'Sedang', 'Dessert', 'https://source.unsplash.com/500x400/?pandan-cake', 280, 5.0, 9.0, 40.0, '2026-02-01 12:16:50'),
(90, 'Wedang Jahe Merah', 'Minuman hangat jahe merah penghangat tubuh', 'Jahe merah 100 gram, gula aren, serai, kayu manis, air', '1. Geprek jahe dan serai\n2. Rebus air hingga mendidih\n3. Masukkan jahe, serai, dan kayu manis\n4. Tambahkan gula aren\n5. Rebus hingga aroma keluar\n6. Saring ke gelas\n7. Sajikan hangat\n8. Selesai. Silahkan dinikmati!', 15, 3, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?ginger-tea', 120, 1.0, 28.0, 0.0, '2026-02-01 12:16:50'),
(91, 'Papeda Kuah Kuning', 'Makanan khas Papua berupa bubur sagu kenyal disajikan dengan ikan kuah kuning rempah', 'Tepung sagu 250 gram, ikan tongkol 500 gram, bawang merah 6 siung, bawang putih 4 siung, kunyit 3 cm, jahe 2 cm, serai 2 batang, daun jeruk 4 lembar, daun kemangi segenggam, air 1.5 liter, garam, gula, minyak, jeruk nipis', '1. Bersihkan ikan dari sisik dan isi perut lalu cuci sampai tidak amis\n2. Lumuri ikan dengan perasan jeruk nipis dan sedikit garam, diamkan 10–15 menit\n3. Bilas kembali lalu potong menjadi beberapa bagian\n4. Haluskan bawang merah, bawang putih, kunyit, dan jahe hingga benar-benar lembut\n5. Geprek serai agar aromanya keluar\n6. Panaskan minyak, tumis bumbu halus bersama serai dan daun jeruk sampai harum dan matang\n7. Tuangkan 1.5 liter air lalu didihkan\n8. Masukkan potongan ikan, masak dengan api sedang hingga ikan matang dan kuah menguning\n9. Tambahkan garam dan gula, koreksi rasa\n10. Masukkan daun kemangi terakhir lalu matikan api\n11. Di panci terpisah didihkan 500 ml air\n12. Masukkan tepung sagu ke mangkuk besar tahan panas\n13. Tuang air mendidih sedikit demi sedikit sambil diaduk cepat menggunakan sendok kayu\n14. Aduk terus hingga adonan berubah bening, kental, dan lengket seperti lem\n15. Ambil papeda dengan sumpit atau garpu kayu, putar hingga menggulung\n16. Sajikan papeda hangat bersama kuah ikan kuning\n17. Selesai. Silahkan dinikmati!', 50, 4, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?papeda', 280, 25.0, 35.0, 8.0, '2026-02-01 12:16:50'),
(92, 'Coto Makassar', 'Sup daging sapi khas Makassar dengan kuah kacang gurih dan rempah kuat', 'Daging sapi 500 gram, jeroan 200 gram, kacang tanah goreng 150 gram, bawang merah 8 siung, bawang putih 5 siung, ketumbar, jintan, merica, lengkuas, serai, daun salam, daun jeruk, garam, minyak, air 2 liter', '1. Cuci bersih daging dan jeroan lalu potong ukuran sedang\n2. Rebus daging dan jeroan selama 45–60 menit hingga empuk, simpan air kaldunya\n3. Angkat daging lalu potong dadu kecil\n4. Haluskan kacang tanah goreng sampai lembut seperti pasta\n5. Haluskan bawang merah, bawang putih, ketumbar, jintan, dan merica\n6. Panaskan minyak lalu tumis bumbu halus sampai harum dan matang\n7. Masukkan lengkuas geprek, serai, daun salam, dan daun jeruk\n8. Tuang bumbu tumis ke dalam panci kaldu\n9. Tambahkan kacang tanah halus sambil diaduk agar tidak menggumpal\n10. Masukkan kembali potongan daging dan jeroan\n11. Masak dengan api kecil 20–30 menit sampai kuah kental dan berminyak\n12. Tambahkan garam secukupnya dan koreksi rasa\n13. Sajikan panas dengan taburan bawang goreng dan daun bawang\n14. Lengkapi dengan lontong atau ketupat\n15. Selesai. Silahkan dinikmati!', 75, 5, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?coto', 520, 35.0, 20.0, 32.0, '2026-02-01 12:16:50'),
(93, 'Es Kacang Merah Palembang', 'Minuman pencuci mulut khas Palembang berisi kacang merah empuk dengan sirup gula dan susu yang manis menyegarkan', 'Kacang merah kering 250 gram, gula merah 150 gram, gula pasir 2 sdm, susu kental manis, santan 300 ml, daun pandan 2 lembar, es batu secukupnya, air 1 liter, garam sedikit', '1. Cuci bersih kacang merah lalu rendam dalam air minimal 4 jam atau semalaman agar cepat empuk\n2. Tiriskan kacang lalu rebus dengan 1 liter air hingga benar-benar lunak dan merekah\n3. Buang buih atau kotoran yang muncul saat merebus\n4. Tambahkan daun pandan agar harum\n5. Masukkan gula merah dan gula pasir, aduk sampai larut dan kuah agak kental\n6. Masak santan terpisah dengan sedikit garam sambil diaduk agar tidak pecah\n7. Siapkan gelas atau mangkuk saji\n8. Masukkan beberapa sendok kacang merah beserta kuahnya\n9. Tambahkan es batu secukupnya\n10. Siram santan dan susu kental manis di atasnya\n11. Aduk perlahan sebelum diminum agar rasa manis gurih tercampur rata\n12. Sajikan dingin agar lebih segar\n13. Selesai. Silahkan dinikmati!', 35, 4, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?red-bean-dessert', 260, 8.0, 48.0, 6.0, '2026-02-01 12:16:50'),
(94, 'Lontong Sayur Labu Siam', 'Lontong dengan kuah santan labu siam gurih khas Betawi', 'Labu siam 2 buah, santan 700 ml, bawang merah, bawang putih, cabai, udang rebon, daun salam, lengkuas, lontong', '1. Kupas dan iris labu siam tipis memanjang\n2. Haluskan bawang, cabai, dan udang rebon\n3. Tumis bumbu hingga harum\n4. Tambahkan daun salam dan lengkuas\n5. Masukkan labu siam dan aduk rata\n6. Tuang santan sambil terus diaduk agar tidak pecah\n7. Masak hingga sayur empuk dan kuah mengental\n8. Bumbui garam dan gula secukupnya\n9. Sajikan bersama potongan lontong dan taburan bawang goreng\n10. Selesai. Silahkan dinikmati!', 40, 4, 'Sedang', 'Sup', 'https://source.unsplash.com/500x400/?lontong-sayur', 390, 12.0, 45.0, 24.0, '2026-02-01 12:16:50'),
(95, 'Bolu Kemojo Riau', 'Kue tradisional Melayu khas Riau bertekstur lembut dengan aroma pandan dan santan yang manis legit', 'Tepung terigu 200 gram, telur 4 butir, gula pasir 180 gram, santan kental 400 ml, margarin cair 100 gram, daun pandan 3 lembar (blender dengan santan), vanili 1/2 sdt, garam 1/2 sdt, wijen secukupnya', '1. Siapkan santan lalu blender bersama daun pandan hingga berwarna hijau dan harum kemudian saring\n2. Kocok telur dan gula pasir menggunakan whisk atau mixer hingga gula larut dan adonan sedikit berbusa\n3. Masukkan margarin cair dan aduk rata\n4. Tuang santan pandan sedikit demi sedikit sambil terus diaduk\n5. Tambahkan tepung terigu, vanili, dan garam lalu aduk hingga adonan halus tanpa gumpalan\n6. Olesi loyang kemojo atau loyang bunga dengan margarin tipis-tipis\n7. Tuang adonan ke dalam loyang sampai hampir penuh\n8. Taburi permukaan dengan wijen sebagai topping\n9. Panaskan oven suhu 170°C selama 10 menit\n10. Panggang adonan selama 35–40 menit hingga matang dan permukaan kecoklatan\n11. Tes tusuk untuk memastikan bagian dalam sudah matang\n12. Keluarkan dari oven lalu biarkan agak dingin\n13. Lepaskan dari loyang dan potong sesuai selera\n14. Sajikan sebagai camilan atau dessert bersama teh hangat\n15. Selesai. Silahkan dinikmati!', 50, 6, 'Sedang', 'Dessert', 'https://source.unsplash.com/500x400/?pandan-cake', 320, 6.0, 42.0, 16.0, '2026-02-01 12:16:50'),
(96, 'Bika Ambon Medan', 'Kue tradisional berserat dengan aroma pandan dan santan khas Medan', 'Tepung tapioka 200 gram, tepung terigu 50 gram, telur 4 butir, gula 200 gram, santan 400 ml, ragi instan 1 sendok teh, daun pandan 2 lembar, kunyit sedikit, garam, mentega untuk olesan', '1. Rebus santan bersama daun pandan dan sedikit kunyit hingga harum sambil diaduk agar tidak pecah\n2. Dinginkan santan sampai hangat kuku\n3. Kocok telur dan gula hingga gula larut dan sedikit berbuih\n4. Campur tepung tapioka, tepung terigu, dan garam dalam wadah besar\n5. Tuangkan campuran telur ke tepung sambil diaduk perlahan\n6. Masukkan santan hangat sedikit demi sedikit hingga adonan licin\n7. Tambahkan ragi instan lalu aduk rata\n8. Tutup adonan dan diamkan 2–3 jam sampai muncul gelembung udara\n9. Panaskan loyang tebal dan olesi mentega tipis\n10. Tuang adonan setinggi 2–3 cm\n11. Panggang api kecil tanpa tutup hingga bagian bawah kecoklatan\n12. Tutup loyang agar bagian atas matang merata\n13. Masak sampai muncul sarang/pori khas bika\n14. Angkat dan dinginkan sepenuhnya sebelum dipotong\n15. Potong persegi dan sajikan\n16. Selesai. Silahkan dinikmati!', 100, 6, 'Sulit', 'Dessert', 'https://source.unsplash.com/500x400/?bika-ambon', 320, 8.0, 55.0, 10.0, '2026-02-01 12:16:50'),
(97, 'Es Teler Medan', 'Minuman pencuci mulut khas Sumatera Utara berisi alpukat, kelapa muda, nangka dan susu manis yang segar', 'Alpukat 2 buah, kelapa muda serut 1 buah, nangka matang 150 gram, susu kental manis 6 sdm, sirup cocopandan 4 sdm, gula cair 3 sdm, es batu secukupnya, air matang 300 ml, biji selasih 1 sdm', '1. Rendam biji selasih dalam air hangat hingga mengembang lalu tiriskan\n2. Belah alpukat, keruk dagingnya lalu potong dadu atau serut memanjang\n3. Iris tipis nangka agar mudah dimakan\n4. Serut daging kelapa muda menggunakan sendok khusus agar teksturnya panjang lembut\n5. Siapkan mangkuk besar atau gelas saji\n6. Masukkan alpukat, kelapa muda, dan nangka ke dalam wadah\n7. Tambahkan biji selasih yang sudah mengembang\n8. Tuang gula cair dan sirup cocopandan untuk memberi rasa manis dan aroma khas\n9. Tambahkan susu kental manis sesuai selera\n10. Masukkan es batu secukupnya agar dingin dan segar\n11. Tuang sedikit air matang supaya kuah lebih ringan\n12. Aduk perlahan hingga semua bahan tercampur rata\n13. Koreksi rasa, tambahkan susu atau sirup jika kurang manis\n14. Sajikan segera selagi dingin agar rasa lebih nikmat dan menyegarkan\n15. Selesai. Silahkan dinikmati!', 15, 3, 'Mudah', 'Minuman', 'https://source.unsplash.com/500x400/?fruit-ice-dessert', 310, 6.0, 48.0, 10.0, '2026-02-01 12:16:50'),
(98, 'Ayam Woku Manado', 'Ayam pedas wangi daun kemangi dan rempah khas Manado', 'Ayam 700 gram, daun kemangi, daun jeruk, serai, kunyit, jahe, cabai merah, bawang merah, bawang putih', '1. Potong ayam dan cuci bersih\n2. Haluskan bumbu cabai, bawang, kunyit, dan jahe\n3. Tumis bumbu sampai harum\n4. Masukkan ayam dan aduk hingga tercampur\n5. Tambahkan sedikit air dan rempah daun jeruk serta serai\n6. Masak hingga ayam empuk dan kuah menyusut\n7. Masukkan daun kemangi terakhir\n8. Aduk sebentar sampai layu\n9. Sajikan hangat\n10. Selesai. Silahkan dinikmati!', 45, 4, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?ayam-woku', 480, 40.0, 12.0, 30.0, '2026-02-01 12:16:50'),
(99, 'Rujak Cingur Surabaya', 'Rujak khas Jawa Timur berisi sayur, buah, lontong, dan cingur dengan saus petis', 'Cingur sapi 300 gram, lontong 2 buah, tauge, kangkung, timun, nanas, bengkuang, tahu goreng, tempe goreng, kacang tanah goreng 150 gram, petis udang 2 sdm, bawang putih, cabai, gula merah, garam, air matang', '1. Bersihkan cingur lalu rebus 1–2 jam hingga benar-benar empuk\n2. Angkat dan potong kecil-kecil\n3. Rebus tauge dan kangkung sebentar lalu tiriskan agar tetap renyah\n4. Potong lontong, tahu, tempe, timun, nanas, dan bengkuang sesuai selera\n5. Haluskan kacang tanah goreng menggunakan cobek sampai lembut\n6. Tambahkan bawang putih, cabai, gula merah, garam, dan petis udang\n7. Ulek hingga semua bumbu tercampur rata\n8. Tambahkan sedikit air matang sampai saus kental dan mudah diaduk\n9. Masukkan semua bahan sayur, buah, lontong, tahu, tempe, dan cingur ke wadah besar\n10. Siram saus petis di atasnya\n11. Aduk perlahan sampai semua bahan terbalut saus\n12. Koreksi rasa manis, asin, pedas\n13. Tambahkan kerupuk atau emping sebagai pelengkap\n14. Sajikan segera selagi segar\n15. Selesai. Silahkan dinikmati!', 55, 4, 'Sedang', 'Makanan Utama', 'https://source.unsplash.com/500x400/?rujak-cingur', 450, 22.0, 55.0, 18.0, '2026-02-01 12:16:50'),
(100, 'Sop Buntut Goreng', 'Buntut sapi empuk digoreng lalu disajikan dengan kuah kaldu gurih', 'Buntut sapi 1 kg, bawang putih, pala, merica, wortel, kentang, daun bawang, seledri, minyak', '1. Rebus buntut hingga empuk selama 1–2 jam, simpan kaldu\n2. Haluskan bawang putih, pala, dan merica\n3. Lumuri buntut dengan bumbu lalu diamkan 20 menit\n4. Goreng buntut hingga kecoklatan\n5. Rebus kembali kaldu bersama wortel dan kentang\n6. Masukkan buntut goreng ke dalam kuah sebentar\n7. Tambahkan garam dan seledri\n8. Sajikan panas dengan sambal dan nasi\n9. Selesai. Silahkan dinikmati!', 120, 4, 'Sedang', 'Sup', 'https://source.unsplash.com/500x400/?sop-buntut', 600, 45.0, 14.0, 42.0, '2026-02-01 12:16:50');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `firebase_uid` varchar(255) NOT NULL,
  `email` varchar(100) NOT NULL,
  `display_name` varchar(100) DEFAULT NULL,
  `photo_url` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `firebase_uid`, `email`, `display_name`, `photo_url`, `created_at`) VALUES
(1, '', 'rayhanfuzy@gmail.com', 'Fuzy', NULL, '2026-02-03 03:27:55'),
(2, 'Ql1pILdtfYbjjSJOsIcitrLRF7q1', '', 'Fuzy', NULL, '2026-02-10 02:45:39');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `favorit`
--
ALTER TABLE `favorit`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `unique_favorit` (`user_id`,`resep_id`),
  ADD KEY `resep_id` (`resep_id`);

--
-- Indexes for table `rating`
--
ALTER TABLE `rating`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`user_id`),
  ADD KEY `resep_id` (`resep_id`);

--
-- Indexes for table `resep`
--
ALTER TABLE `resep`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `firebase_uid` (`firebase_uid`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `favorit`
--
ALTER TABLE `favorit`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=28;

--
-- AUTO_INCREMENT for table `rating`
--
ALTER TABLE `rating`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `resep`
--
ALTER TABLE `resep`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `favorit`
--
ALTER TABLE `favorit`
  ADD CONSTRAINT `favorit_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `favorit_ibfk_2` FOREIGN KEY (`resep_id`) REFERENCES `resep` (`id`) ON DELETE CASCADE;

--
-- Constraints for table `rating`
--
ALTER TABLE `rating`
  ADD CONSTRAINT `rating_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `rating_ibfk_2` FOREIGN KEY (`resep_id`) REFERENCES `resep` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
